stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - name: compile
      stage: compile
      language: go
      go: 1.12.x
      script: 
        - env GO111MODULE=on go build .
    - name: lint
      stage: test
      language: go
      go: 1.12.x
      before_script:
        - export GO111MODULE=off
        - go get golang.org/x/lint/golint
      script: 
        - golint --set_exit_status ./...
        - if [[ $(env GO111MODULE=on gofmt -s -l .) ]]; then env GO111MODULE=on gofmt -s -l .; exit 1; fi 
        - if [[ $(env GO111MODULE=on goimports -l .) ]]; then env GO111MODULE=on goimports -l .; exit 1; fi
    - name: test
      stage: test
      language: go
      go: 1.12.x
      script: 
        - env GO111MODULE=on go test ./... -race
    - name: coverage
      stage: test
      language: go
      go: 1.12.x
      before_install: go get github.com/mattn/goveralls
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: 
        - mandatory_coverage="90"
        - env GO111MODULE=on go test ./... -coverprofile=c.out
        - env GO111MODULE=on go tool cover -func=c.out > coverage.txt
        - coverage_percent=$(grep -Eo "total:.*\(statements\).*[0-9.]+" coverage.txt | grep -Eo "[0-9]+\.[0-9]+" | bc) # I am not good at bash
        - if [ $(bc -l <<< "$coverage_percent < $mandatory_coverage") -eq 1 ]; then echo "Coverage percentage was ${coverage_percent}%, must be at least ${mandatory_coverage}%!"; exit 1; else echo "Coverage percentage was ${coverage_percent}%, mandatory coverage is ${mandatory_coverage}%"; fi
      after_script:
        - $GOPATH/bin/goveralls -coverprofile=c.out -service=travis-ci
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - name: deploy
      stage: deploy
      language: go
      go: 1.12.x
      script: 
        - exit 0 # write deployment code