stages:
  - compile
  - test
  - report
  - name: deploy
    if: branch = master

jobs:
  include:
    - name: server
      stage: compile
      language: go
      go: 1.12.x
      script: go build -o server.o ./server 
    - name: ui
      stage: compile
      language: node_js
      node_js: 10
      cache:
        directories:
          - node_modules
      install:
        - cd ui; npm install
      script: npm run build
    - name: server lint
      stage: test
      language: go
      go: 1.12.x
      before_script:
        - export GO111MODULE=off
        - go get golang.org/x/lint/golint
        - export GO111MODULE=auto
      script: 
        - golint --set_exit_status ./...
        - if [[ $(gofmt -s -l .) ]]; then gofmt -s -l .; exit 1; fi 
        - if [[ $(goimports -l .) ]]; then goimports -l .; exit 1; fi
    - name: server test
      stage: test
      language: go
      go: 1.12.x
      script: 
        - go test ./server/internal/... -race
    - name: server coverage
      stage: test
      language: go
      go: 1.12.x
      script: 
        - mandatory_coverage="90"
        - mkdir coverage
        - go test ./server/internal/... -coverprofile=c.out
        - go tool cover -func=c.out > coverage/coverage.txt
        - coverage_percent=$(grep -Eo "total:.*\(statements\).*[0-9.]+" coverage/coverage.txt | grep -Eo "[0-9]+\.[0-9]+" | bc) # I am not good at bash
        - if [ $(bc -l <<< "$coverage_percent < $mandatory_coverage") -eq 1 ]; then echo "Coverage percentage was ${coverage_percent}, must be at least ${mandatory_coverage}!"; exit 1; fi
      deploy:
        provider: s3
        access_key_id: $S3_ACCESS_KEY_ID
        secret_access_key: $S3_SECRET_ACCESS_KEY
        bucket: "lukekennedy-net-travis"
        skip_cleanup: true
        local_dir: coverage
        upload_dir: $TRAVIS_BUILD_NUMBER/server
    - name: ui
      stage: test
      language: node_js
      node_js: 10
      cache:
        directories:
          - node_modules
      install:
        - cd ui; npm install
      script: npm run test
      deploy:
        provider: s3
        access_key_id: $S3_ACCESS_KEY_ID
        secret_access_key: $S3_SECRET_ACCESS_KEY
        bucket: "lukekennedy-net-travis"
        skip_cleanup: true
        local_dir: coverage
        upload_dir: $TRAVIS_BUILD_NUMBER/ui
    - name: server
      stage: deploy
      language: go
      go: 1.12.x
      script: exit 0 # write deployment code
    - name: ui
      stage: deploy
      language: node_js
      node_js: 10
      cache:
        directories:
          - node_modules
      install:
        - cd ui; npm install
      script: exit 0 # write deployment code
    - name: 
      stage: report
      language: